name: swiftie_game
description: A Taylor Swiftâ€“themed guessing game ğŸ¤
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  confetti: ^0.8.0
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  audioplayers: ^6.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/win/
    - assets/images/lose/
    - assets/images/home_image.png
    - assets/images/home.jpg
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/home_image.png"


flutter_native_splash:
  color: "#6A0DAD"
  image: assets/images/home.jpg
  android: true
  ios: true
  fullscreen: true